### Numpy array vs python list

#### speed

In [1]:
#List 
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

1.8584973812103271


In [2]:
#numpy array
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start=time.time()
c=a+b
print(time.time()-start)

0.11289763450622559


In [3]:
1.5812489986419678/0.015096902847290039

104.73995988692535

#### memory

In [4]:
a=[i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [5]:
a=np.arange(10000000)

sys.getsizeof(a)

40000104

In [6]:
#list can store homogeneous data, but in numpy we can not 
#-- store the homogeneous data

### Advanced Indexing

##### Normal Indexing

In [7]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a[1,2]

6

#### Fancy Indexing

In [9]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
#Extract 1,3,4 rows
b[[0,2,3]]
#it is not possible in normal indexing

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
#extract 1,3 columns
b[:,[0,2]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

#### Boolean Indexing

In [12]:
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[ 9, 82, 18, 11],
       [60, 45, 13, 14],
       [91, 31, 32, 56],
       [77, 21, 74, 27],
       [37, 67, 76, 14],
       [ 4, 13, 89, 28]])

In [13]:
#find all numbers greater than 50
a>50

array([[False,  True, False, False],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False]])

In [14]:

a[a>50]

array([82, 60, 91, 56, 77, 74, 67, 76, 89])

In [15]:
#find out even numbers
a%2==0

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True],
       [False, False,  True, False],
       [False, False,  True,  True],
       [ True, False, False,  True]])

In [16]:
a[a%2==0]

array([82, 18, 60, 14, 32, 56, 74, 76, 14,  4, 28])

In [17]:
#find all the numbers greater than 5o and even 

In [18]:
(a>50) & (a%2==0)

array([[False,  True, False, False],
       [ True, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [19]:
a[(a>50) & (a%2==0)]

array([82, 60, 56, 74, 76])

In [20]:
#find all the numbers divisible by 7
a[a%7==0]

array([14, 91, 56, 77, 21, 14, 28])

### Broadcasting

In [21]:
a=np.arange(12).reshape(4,3)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [22]:
a=np.arange(12).reshape(3,4)
b=np.arange(3)
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [23]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [24]:
a=np.arange(3).reshape(1,3)
b=np.arange(4).reshape(4,1)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [25]:
a=np.array([1])
b=np.arange(4).reshape(2,2)
print(a+b)

[[1 2]
 [3 4]]


In [26]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a=np.arange(16).reshpae(4,4)
b=np.arange(4).reshape(2,2)
print(a+b)

### Working with mathematical formulas

In [ ]:
a=np.arange(10)
a

In [ ]:
np.sin(a)

In [ ]:
np.sum(a)

#### Sigmoid

In [ ]:
# sigmoid formula : 1/(1+e*-x)

In [ ]:
def sigmoid(array):
    return 1/(1+np.exp(-(array)))

a=np.arange(10)
sigmoid(a)

#### mean squared error

In [ ]:
#mse formula =(actual - predicted)**2

In [ ]:
actual=np.random.randint(1,50,25)
actual

In [ ]:
predicted=np.random.randint(1,50,25)
predicted

In [ ]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)
    
mse(actual,predicted)

#### binary cross entropy

### Working with missing values

In [ ]:
a=np.array([1,2,3,4,np.nan,6])
a

In [ ]:
np.isnan(a)

In [ ]:
a[~np.isnan(a)]

### Plotting Graphs

In [ ]:
#2D plot x=y
x=np.linspace(-10,10,100)
x
y=x

In [ ]:
import matplotlib.pyplot as plt
plt.plot(x,y)

In [ ]:
#if y=x*2
x=np.linspace(-10,10,100)
y=x**2
plt.plot(x,y)

In [ ]:
#y=sin(x)
x=np.linspace(-10,10,100)
y=np.sin(x)
plt.plot(x,y)

In [ ]:
#sigmoid
x=np.linspace(-10,10,100)
y=1/(1+np.exp(-x))
plt.plot(x,y)

### Plotting 3D Graph

In [ ]:
import numpy as np

In [ ]:
#meshgrid
a=np.linspace(0,2,3)
b=np.linspace(0,2,3)

In [ ]:
np.meshgrid(a,b)

In [ ]:
xx,yy=np.meshgrid(a,b)

In [ ]:
xx

In [ ]:
yy

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(xx,yy)

In [ ]:
def fun(x,y):
    return x**2+y**2
zz=fun(xx,yy)

In [ ]:
print(zz)

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
fig=px.scatter_3d()
fig.add_trace(go.Surface(x=xx,y=yy,z=zz))
fig.show()