#### Creating Numpy array

In [1]:
import numpy as np

In [5]:
#1D array
a=np.array([1,2,3,4])
print(a)
print(type(a))
#it also called as vector

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
print(a)
#it is also called as metrix

[[1 2 3]
 [4 5 6]]


In [8]:
#3D array
c=np.array([[[1,2],[2,3]],[[5,6],[7,8]]])
print(c)
#it is also called as tensor 

[[[1 2]
  [2 3]]

 [[5 6]
  [7 8]]]


### dtype

In [9]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [10]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [11]:
np.array([1,2,3,4],dtype=int)

array([1, 2, 3, 4])

### np. arange

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### with reshape

In [18]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### np.ones and np.zeros

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### np.random

In [25]:
np.random.random((3,4))

array([[0.76655007, 0.62329852, 0.79679419, 0.10689892],
       [0.01536686, 0.59458483, 0.84595949, 0.5137398 ],
       [0.71901479, 0.43539579, 0.60588873, 0.75449494]])

In [27]:
np.random.random((2,2))

array([[0.25691127, 0.46309646],
       [0.01624637, 0.95351895]])

In [29]:
np.random.random((4,4))
# (4,4) is the size of the metrix

array([[0.92460219, 0.32541398, 0.64116854, 0.7835469 ],
       [0.97000454, 0.87729583, 0.59581597, 0.06687752],
       [0.43983155, 0.49411369, 0.32052513, 0.60585747],
       [0.13096873, 0.77207681, 0.33363082, 0.49226295]])

### np.linspace(Linearly Spacede)

In [31]:
np.linspace(-10,10,10)
#-10 to 10 the linearly spaced 10 points
#the distance beatween each point is equal

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [32]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

### np.identity

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

1.ndim
2.shape
3.size
4.itemsize
5.dtype

In [38]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

##### ndim(Number of Dimenssions)

In [49]:

a1.ndim

1

In [41]:
a2.ndim

2

In [42]:
a3.ndim

3

#### shape

In [43]:

a1.shape

(10,)

In [44]:
a2.shape

(3, 4)

In [48]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
#2 items of 2*2 metrix

#### size

In [52]:
print(a2.size)

12


In [53]:
a3.size

8

In [54]:
a1.size

10

In [55]:
#Number of items present in an array

#### itemsize  (item size refers to memory)

In [56]:
a1.itemsize
# 4 bytes 

4

In [59]:
a2.itemsize
#8 bytes

8

In [61]:
a3.itemsize
#4 bytes

4

#### dtype

In [62]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [63]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
print(a3.dtype)

int32


In [65]:
#astype used to reduce the size.

### Array Operations

In [67]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [68]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Scalar Operation

In [ ]:
#scalar operations works on single

#### arithematic operators

In [70]:

a2*2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [71]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [72]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [73]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [74]:
a1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [77]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [79]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

##### Relational Operators

In [80]:
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [81]:
a1==9

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [82]:
a2<30

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### Vector Operations

#### Arithematic Operations

In [84]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

### Array Functions

In [89]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[76., 91.,  3.],
       [34., 50., 85.],
       [55., 43., 54.]])

In [90]:
np.min(a1)

3.0

In [91]:
np.max(a1)

91.0

In [92]:
np.sum(a1)

491.0

In [93]:
np.prod(a1)

382885563060000.0

In [94]:
#0-> COLUMN AND 1-> ROW

In [96]:
np.max(a1,axis=0)

array([76., 91., 85.])

In [101]:
np.max(a1,axis=1)
#max value of rows

array([91., 85., 55.])

In [100]:
np.min(a1,axis=1)
#min value of rows 

array([ 3., 34., 43.])

In [102]:
np.mean(a1)

54.55555555555556

In [103]:
np.mean(a1,axis=1)

array([56.66666667, 56.33333333, 50.66666667])

In [104]:
np.median(a1)

54.0

In [105]:
np.median(a1,axis=1)

array([76., 50., 54.])

In [107]:
#trigonametric functions
np.sin(a1)

array([[ 0.56610764,  0.10598751,  0.14112001],
       [ 0.52908269, -0.26237485, -0.17607562],
       [-0.99975517, -0.83177474, -0.55878905]])

In [108]:
#dot product 
# for dot product first metrix colums should match for second metrix columns

In [111]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [112]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [113]:
#log
np.log(a1)

array([[4.33073334, 4.51085951, 1.09861229],
       [3.52636052, 3.91202301, 4.44265126],
       [4.00733319, 3.76120012, 3.98898405]])

In [114]:
#exponential
np.exp(a1)

array([[1.01480039e+33, 3.31740010e+39, 2.00855369e+01],
       [5.83461743e+14, 5.18470553e+21, 8.22301271e+36],
       [7.69478527e+23, 4.72783947e+18, 2.83075330e+23]])

In [121]:
#round
np.round(np.random.random((2,3))*100)

array([[68., 86., 75.],
       [98., 19., 75.]])

In [123]:
#floor
np.floor(np.random.random((2,3))*100)

array([[28., 47., 54.],
       [12., 39., 59.]])

In [124]:
#ceil
np.ceil(np.random.random((2,3))*100)

array([[ 6., 12., 94.],
       [79., 29., 74.]])

### indexing and slicing

#### indexing

In [126]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [127]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
#extract 6
#[row index, column index]
a2[1,2]
#first is row and second is column
#indexing starts from 0 -> remember

6

In [131]:
#extract 11
a2[2,3]

11

In [132]:
#extract 0
a2[0,0]

0

In [134]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [138]:
#extract 5 
#in 3D array there is two 2d arrays
a3[1,0,1]
# 2nd metrix index is - 1
# 2nd metrix first row index is - 0
# 2nd metrix second column index is - 1

#[metrix index, row index, column index]

5

In [137]:
#extract 2

a3[0,1,0]

2

In [139]:
#extract 7
a3[1,1,1]

7

In [140]:
#Extract 4

a3[1,0,0]

4

In [141]:
#extract 6
a3[1,1,0]

6

#### Slicing

In [143]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
#extract 2 to 4

a1[2:5]

array([2, 3, 4])

In [145]:
a1[6:9]

array([6, 7, 8])

In [146]:
a1[2:8:2]

array([2, 4, 6])

In [147]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
#extract first row
a2[0,:]
#[index of column,index of row]

array([0, 1, 2, 3])

In [152]:
#extract first row 1 to 3
a2[0,1:]

array([1, 2, 3])

In [155]:
#extract 3rd column
a2[:,2]

array([ 2,  6, 10])

In [157]:
#Extract 
#  5  6
# 9  10  

In [160]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [164]:
#extract 0  1
#        4  5
a2[0:2,0:2]
#[row index and column index]

array([[0, 1],
       [4, 5]])

In [165]:
# extract 6   7
#         10  11
a2[1:3,2:]

array([[ 6,  7],
       [10, 11]])

In [166]:
#Extract 1   2 
#        5   6
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [169]:
# Extract 0     3

#        8      11

a2[::2,::3]
#all rows step value is 2
#all columns step value is 3

array([[ 0,  3],
       [ 8, 11]])

In [170]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Extract 1     3
#         9     11

In [171]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [176]:
#extract 1  2  3
#        5  6  7
a2[0:2:,1:4:]

array([[1, 2, 3],
       [5, 6, 7]])

In [178]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
#extract 1    3
#        5    7

In [183]:
a2[0:2:,1::2]

array([[1, 3],
       [5, 7]])

In [184]:
#slicing for 3D array

In [185]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [187]:
a4=np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [188]:
a4[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [189]:
a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [190]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [192]:
a4


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [191]:
#extract 1st matrix 2nd row
a4[0,1,:]

array([3, 4, 5])

In [193]:
#extract 18,19,20
a4[2,0,:]

array([18, 19, 20])

In [195]:
a4[1,:,1]

array([10, 13, 16])

In [196]:
# extract 22 23
#         25 26
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [197]:
a4[1,0:2,1:]

array([[10, 11],
       [13, 14]])

In [198]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#  extract   18 19 20
#            21 22 23

In [199]:
a4[2,0:2,:]

array([[18, 19, 20],
       [21, 22, 23]])

In [203]:
# extract 0        2
#         18       20
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### iterating

In [204]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [207]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [208]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [210]:
for i in a4:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [211]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [212]:
for i in np.nditer(a4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [213]:
for i in np.nditer(a1):
    print(i)

0
1
2
3
4
5
6
7
8
9


### Reshaping

In [214]:
np.transpose(a3)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [215]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [216]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [217]:
a4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [225]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [226]:
np.hstack((a4,a5))
#horizontal stacking

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical stacking

In [227]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [228]:
#stacking is used for combine multiple data sources

### Spliting 

In [229]:
#horizontal spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [230]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [231]:
#Where 2 is number of parts of split

In [232]:
#vertical split
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]