#### np.sort

In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,10)
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[90, 81, 70, 22],
       [ 1, 14, 86, 34],
       [28, 45, 89, 40],
       [10, 29, 48, 83],
       [58, 71,  1,  3],
       [ 6, 42, 65, 78]])

In [4]:
np.sort(a)

array([ 8, 10, 17, 41, 41, 47, 50, 71, 72, 93])

In [5]:
#Reverse Sort
np.sort(a)[::-1]

array([93, 72, 71, 50, 47, 41, 41, 17, 10,  8])

In [6]:
np.sort(b)

array([[22, 70, 81, 90],
       [ 1, 14, 34, 86],
       [28, 40, 45, 89],
       [10, 29, 48, 83],
       [ 1,  3, 58, 71],
       [ 6, 42, 65, 78]])

In [7]:
#column wise sorting
np.sort(b,axis=0)

array([[ 1, 14,  1,  3],
       [ 6, 29, 48, 22],
       [10, 42, 65, 34],
       [28, 45, 70, 40],
       [58, 71, 86, 78],
       [90, 81, 89, 83]])

#### np.upend

In [8]:
np.append(a,200)

array([ 41,  17,  93,  10,  72,   8,  47,  71,  50,  41, 200])

In [9]:
#inserting one new column in 2D array

In [10]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[9.00000000e+01, 8.10000000e+01, 7.00000000e+01, 2.20000000e+01,
        3.04024405e-01],
       [1.00000000e+00, 1.40000000e+01, 8.60000000e+01, 3.40000000e+01,
        3.49624784e-01],
       [2.80000000e+01, 4.50000000e+01, 8.90000000e+01, 4.00000000e+01,
        2.05229946e-01],
       [1.00000000e+01, 2.90000000e+01, 4.80000000e+01, 8.30000000e+01,
        3.66981599e-02],
       [5.80000000e+01, 7.10000000e+01, 1.00000000e+00, 3.00000000e+00,
        7.31720810e-01],
       [6.00000000e+00, 4.20000000e+01, 6.50000000e+01, 7.80000000e+01,
        3.49157876e-01]])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[90., 81., 70., 22.,  1.],
       [ 1., 14., 86., 34.,  1.],
       [28., 45., 89., 40.,  1.],
       [10., 29., 48., 83.,  1.],
       [58., 71.,  1.,  3.,  1.],
       [ 6., 42., 65., 78.,  1.]])

#### np.concatenate

In [12]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### np.unique

In [15]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### np.expand_dims

In [17]:
#we can get the expanded dimensions of an array

In [18]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [19]:
a.shape

(10,)

In [20]:
np.expand_dims(a,axis=0)

array([[41, 17, 93, 10, 72,  8, 47, 71, 50, 41]])

In [21]:
np.expand_dims(a,axis=0).shape

(1, 10)

In [22]:
np.expand_dims(a,axis=1)

array([[41],
       [17],
       [93],
       [10],
       [72],
       [ 8],
       [47],
       [71],
       [50],
       [41]])

In [23]:
np.expand_dims(a,axis=1).shape

(10, 1)

#### np.where

In [24]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [25]:
#find all indices with value greater than 50

In [26]:
np.where(a>50)

(array([2, 4, 7], dtype=int64),)

In [27]:
# 0,2,4,7,9 these are index positions

In [28]:
np.where(a>50,0,a)
#(condition, True,False)

array([41, 17,  0, 10,  0,  8, 47,  0, 50, 41])

In [29]:
np.where(a%2==0,0,a)

array([41, 17, 93,  0,  0,  0, 47, 71,  0, 41])

### np.argmax

In [30]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [31]:
np.argmax(a)

2

In [32]:
#max value is 93 and index position is 2

In [33]:
b

array([[90, 81, 70, 22],
       [ 1, 14, 86, 34],
       [28, 45, 89, 40],
       [10, 29, 48, 83],
       [58, 71,  1,  3],
       [ 6, 42, 65, 78]])

In [34]:
np.argmax(b,axis=1)
#it will return the row wise max value position of a index number 

array([0, 2, 2, 3, 1, 3], dtype=int64)

In [36]:
np.argmax(b,axis=0)
#it will return the column wise max value position of a index number 

array([0, 0, 2, 3], dtype=int64)

### np.argmin

In [38]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [39]:
np.argmin(a)

5

In [40]:
b

array([[90, 81, 70, 22],
       [ 1, 14, 86, 34],
       [28, 45, 89, 40],
       [10, 29, 48, 83],
       [58, 71,  1,  3],
       [ 6, 42, 65, 78]])

In [41]:
np.argmin(b,axis=0) # column wise

array([1, 1, 4, 4], dtype=int64)

In [42]:
np.argmin(b,axis=1) #row wise

array([3, 0, 0, 0, 2, 0], dtype=int64)

### np.cumsum

In [43]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [44]:
np.cumsum(a)

array([ 41,  58, 151, 161, 233, 241, 288, 359, 409, 450], dtype=int32)

In [45]:
b

array([[90, 81, 70, 22],
       [ 1, 14, 86, 34],
       [28, 45, 89, 40],
       [10, 29, 48, 83],
       [58, 71,  1,  3],
       [ 6, 42, 65, 78]])

In [51]:
np.cumsum(b)

array([  90,  171,  241,  263,  264,  278,  364,  398,  426,  471,  560,
        600,  610,  639,  687,  770,  828,  899,  900,  903,  909,  951,
       1016, 1094], dtype=int32)

In [47]:
np.cumsum(b,axis=1)
#cumsum along the row 

array([[ 90, 171, 241, 263],
       [  1,  15, 101, 135],
       [ 28,  73, 162, 202],
       [ 10,  39,  87, 170],
       [ 58, 129, 130, 133],
       [  6,  48, 113, 191]], dtype=int32)

In [49]:
np.cumsum(b,axis=0)
#cum sum along the column 

array([[ 90,  81,  70,  22],
       [ 91,  95, 156,  56],
       [119, 140, 245,  96],
       [129, 169, 293, 179],
       [187, 240, 294, 182],
       [193, 282, 359, 260]], dtype=int32)

### np.cumprod

In [52]:
np.cumprod(a)

array([         41,         697,       64821,      648210,    46671120,
         373368960,   368471936,   391703680, -1889652480,  -166340352],
      dtype=int32)

In [53]:
b

array([[90, 81, 70, 22],
       [ 1, 14, 86, 34],
       [28, 45, 89, 40],
       [10, 29, 48, 83],
       [58, 71,  1,  3],
       [ 6, 42, 65, 78]])

In [55]:
np.cumprod(b,axis=0)

array([[        90,         81,         70,         22],
       [        90,       1134,       6020,        748],
       [      2520,      51030,     535780,      29920],
       [     25200,    1479870,   25717440,    2483360],
       [   1461600,  105070770,   25717440,    7450080],
       [   8769600,  118005044, 1671633600,  581106240]], dtype=int32)

In [56]:
np.cumprod(b,axis=1)

array([[      90,     7290,   510300, 11226600],
       [       1,       14,     1204,    40936],
       [      28,     1260,   112140,  4485600],
       [      10,      290,    13920,  1155360],
       [      58,     4118,     4118,    12354],
       [       6,      252,    16380,  1277640]], dtype=int32)

### np.percentile

In [57]:
#function used to compute the nth percentile of the given data (array element) along the specified axis

In [58]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [60]:
np.percentile(a,100)
#100th percentile
#max value in an array

93.0

In [61]:
np.percentile(a,0)
#50th percentile
#min value in an array

8.0

In [63]:
np.percentile(a,50)
#median

44.0

In [65]:
#percentile formula (n/N)*100
#where 'n' is number of values below 'x'
#where 'N' is total count of population 

### np.histogram

In [66]:
#Function which represents the frequency of data distribution in the graphical form.

In [67]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [69]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 0, 0, 3, 1, 0, 2, 0, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
0 t0 10 --> 1 item (8)
10 to 20 ---> 2 items (17,10)
30 to 40 ---> 0 items

In [70]:
np.histogram(a,bins=[0,50,100])

(array([6, 4], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

In [ ]:
#Returns Pearson product-moment correlation coefficient

In [72]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

In [73]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [74]:
items=[10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False,  True, False, False, False, False,  True,
       False])

In [75]:
a[np.isin(a,items)]

array([10, 50])

### np.flip

In [76]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [77]:
np.flip(a)

array([41, 50, 71, 47,  8, 72, 10, 93, 17, 41])

In [78]:
b

array([[90, 81, 70, 22],
       [ 1, 14, 86, 34],
       [28, 45, 89, 40],
       [10, 29, 48, 83],
       [58, 71,  1,  3],
       [ 6, 42, 65, 78]])

In [79]:
np.flip(b)

array([[78, 65, 42,  6],
       [ 3,  1, 71, 58],
       [83, 48, 29, 10],
       [40, 89, 45, 28],
       [34, 86, 14,  1],
       [22, 70, 81, 90]])

In [80]:
np.flip(b,axis=0)

array([[ 6, 42, 65, 78],
       [58, 71,  1,  3],
       [10, 29, 48, 83],
       [28, 45, 89, 40],
       [ 1, 14, 86, 34],
       [90, 81, 70, 22]])

In [81]:
np.flip(b,axis=1)

array([[22, 70, 81, 90],
       [34, 86, 14,  1],
       [40, 89, 45, 28],
       [83, 48, 29, 10],
       [ 3,  1, 71, 58],
       [78, 65, 42,  6]])

### np.put

In [83]:
a

array([41, 17, 93, 10, 72,  8, 47, 71, 50, 41])

In [85]:
np.put(a,[0,1],[410,170])

In [86]:
#permanent changes 

In [87]:
print(a)

[410 170  93  10  72   8  47  71  50  41]


### np.delete

In [88]:
a

array([410, 170,  93,  10,  72,   8,  47,  71,  50,  41])

In [92]:
np.delete(a,0)

array([170,  93,  10,  72,   8,  47,  71,  50,  41])

In [94]:
np.delete(a,[0,1,2])

array([10, 72,  8, 47, 71, 50, 41])

In [ ]:
#if the output given its temporary
#if the output not given its permanent 

# set functions

In [96]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [98]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [101]:
np.intersect1d(m,n)

array([3, 4, 5])

In [102]:
np.setdiff1d(m,n)

array([1, 2])

In [103]:
np.setdiff1d(n,m)

array([6, 7])

In [104]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [105]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [106]:
np.in1d(n,8)

array([False, False, False, False, False])

### np.clip

In [107]:
a

array([410, 170,  93,  10,  72,   8,  47,  71,  50,  41])

In [110]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 72, 25, 47, 71, 50, 41])